name: hello
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_compass: ^0.8.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  camera: ^0.11.2+1
  record: ^6.1.2
  audioplayers: ^6.5.1
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  path: ^1.9.1
  image_gallery_saver_plus: ^4.0.1
  intl: ^0.20.2
  http: ^1.5.0
  url_launcher: ^6.3.2
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  percent_indicator: ^4.2.5
  pedometer: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/